#!/bin/bash
clear
loop=y
while [ "$loop" = "y" ] || [ "$loop" = "Y" ]
do
echo "           Add New Lab Equipment Form"
echo "          ============================"

read -p "Stock Code                 : " stockCode
stock="^S[0-9]{5}$"
 while [[ ! $stockCode =~ $stock ]]; 
 do
  echo "Invalid Stock Code."; read -p "Stock Code                 : " stockCode
 done

read -p "Manufacturer               : " manufacturer
read -p "Model                      : " model
read -p "Item Description           : " itemdesc
read -p "Serial Number              : " serialnum
serial="^[0-9]{2}-[0-9]{4}-[0-9]{5}$"
 while [[ ! $serialnum =~ $serial ]]; 
 do
  echo "Invalid Serial Number."; read -p "Serial Number              : " serialnum
 done
read -p "Status (default-Available) : " status
status=${status:-Available}

echo "Adding new lab equipment..."
sleep 2
echo "$stockCode:$manufacturer:$model:$itemdesc:$serialnum:$status" >> equipment.txt

echo -n "Add Another New Equipment? (y)es or (q)uit :"

echo "Press (q) to return to" $(tput bold)"Lab Equipment"$(tput sgr0) " Management Menu."
read choice
 if [ "$choice" = "q" ] || [ "$choice" = "Q" ]
 then 
  ./main_menu
  break
 fi

done

