#!/bin/bash
clear
echo "Register New Student Form"
echo "============================"

loop=y
student=student.txt
while [ "$loop" = "y" ] || [ "$loop" = "Y" ]
do
 read -p "Student ID              : " studid
 id="^[0-9]{2}[WMR]{3}[0-9]{5}$"
 while [[ ! $studid =~ $id ]]; 
 do
  echo "Invalid Student ID."; read -p "Student ID              : " studid
 done
 
 read -p "Full Name (As per NRIC) : " fullname
 name=""
 while [[ ! $fullname =~ $name ]]; 
 do
  echo "Full Name must not empty."; read -p "Full Name (As per NRIC) : " fullname
 done

 read -p "Contact Number          : " contactnum
 telnum="^[0-9]{3}-[0-9]{7,8}$"
 while [[ ! $contactnum =~ $telnum ]]; 
 do
  echo "Invalid Contact Number."; read -p "Contact Number          : " contactnum
 done
 
 read -p "TAR UC Email Address    : " email
 mail="^[a-z0-9]{1,}@student.tarc.edu.my$"
 while [[ ! $email =~ $mail ]]; 
 do
  echo "Invalid Email Address."; read -p "TAR UC Email Address    : " email
 done
 
echo "Registering new student..."
sleep 2
echo "$studid:$fullname:$contactnum:$email" >> student.txt

echo -n  "Register Another Student? (y)es or (q)uit :"
echo 
echo "Press (q) to return to" $(tput bold)"Lab Equipment"$(tput sgr0) " Management Menu."
read choice
 if [ "$choice" = "q" ] || [ "$choice" = "Q" ]
 then 
  ./main_menu
  break
 fi


done

